/**
 * Visible AI disclosure copy outside the website (EU AI Act Art. 50(4)): RSS, public API docs,
 * newsletter, social posts and bios, podcast, carousel. Approved by the owner on 2026-09-25
 * (label copy review, items ACR-5 to ACR-11, ACR-17, ACR-18). The website's copy lives in
 * client/src/components/ai/aiDisclosureCopy.ts. Change wording here, not at the call sites,
 * and update .context/ai-transparency.md in the same change.
 */

/** Prefix of every RSS item description. */
export const RSS_ITEM_PREFIX = '[AI-generated] '

/** RSS channel description; per-issue feeds lead with the issue name. */
export function rssChannelDescription(issueName?: string): string {
  if (!issueName) return 'News that matters to humanity. Written and curated by AI.'
  return `${issueName}: news that matters to humanity. Written and curated by AI.`
}

/** Note to republishers in the OpenAPI `info.description`. */
export const OPENAPI_REPUBLISHER_NOTE =
  'Story titles, labels, summaries, blurbs, and analyses are generated by AI and are not reviewed by an editor. ' +
  'If you republish them, label them as AI-generated.'

/** First sentence of every AI-generated field's OpenAPI description. */
export const OPENAPI_AI_FIELD_PREFIX = 'AI-generated. '

/** Newsletter label directly under the week title; the lead-in is set in bold. */
export const NEWSLETTER_TOP_LABEL = {
  lead: 'AI-generated:',
  text: 'AI selected the stories in this issue and wrote the intro, headlines, and summaries.',
} as const

/** Last segment of the metadata line in every Bluesky and Mastodon post. */
export const SOCIAL_POST_AI_SEGMENT = 'AI-generated'

/** Bio of the automated Bluesky and Mastodon accounts. */
export function socialBotBio(sourceCount: number): string {
  return `Automated account. Posts are generated by AI from ${sourceCount} news sources. actuallyrelevant.news`
}

/** Spoken first line of every podcast script (the TTS voice reads the script word by word). */
export const PODCAST_OPENER = 'This is an AI-generated voice.'

/** Carousel: pixel footer on every slide, the post text line, and the alt-text prefix. */
export const CAROUSEL_COPY = {
  slideFooter: 'actuallyrelevant.news · AI-generated',
  postText: 'The headlines and summaries in these slides are AI-generated.',
  altTextPrefix: 'AI-generated summary: ',
} as const
