/**
 * Visible AI disclosure copy outside the website (EU AI Act Art. 50(4)): RSS, public API docs,
 * newsletter, social posts and bios, podcast, carousel. Approved by the owner on 2026-09-25
 * (label copy review, items ACR-5 to ACR-11, ACR-17, ACR-18). The website's copy lives in
 * client/src/components/ai/aiDisclosureCopy.ts. Change wording here, not at the call sites,
 * and update .context/ai-transparency.md in the same change.
 */

/** Prefix of every RSS item description. */
export const RSS_ITEM_PREFIX = '[AI-generated] '

/** RSS channel description; per-issue feeds lead with the issue name. */
export function rssChannelDescription(issueName?: string): string {
  if (!issueName) return 'News that matters to humanity. Written and curated by AI.'
  return `${issueName}: news that matters to humanity. Written and curated by AI.`
}

/** Note to republishers in the OpenAPI `info.description`. */
export const OPENAPI_REPUBLISHER_NOTE =
  'Story titles, labels, summaries, blurbs, and analyses are generated by AI and are not reviewed by an editor. ' +
  'If you republish them, label them as AI-generated.'

/** First sentence of every AI-generated field's OpenAPI description. */
export const OPENAPI_AI_FIELD_PREFIX = 'AI-generated. '

/** Newsletter label directly under the week title; the lead-in is set in bold. */
export const NEWSLETTER_TOP_LABEL = {
  lead: 'AI-generated:',
  text: 'AI selected the stories in this issue and wrote the intro, headlines, and summaries.',
} as const

/** Last segment of the metadata line in every Bluesky and Mastodon post. */
export const SOCIAL_POST_AI_SEGMENT = 'AI-generated'

/** Bio of the automated Bluesky and Mastodon accounts. */
export function socialBotBio(sourceCount: number): string {
  return `Automated account. Posts are generated by AI from ${sourceCount} news sources. actuallyrelevant.news`
}

/**
 * Spoken first turn of every podcast episode (HOST_A), added in code before the model's dialogue.
 * Approved by the owner on 2026-10-06 (after the Phase 1 review), replacing the 2026-10-05 wording.
 */
export const PODCAST_OPENER = "Everything you're about to hear was written and voiced by AI from this week's news."

/**
 * First line of every episode's show notes (and, from publication on, its feed description).
 * Approved by the owner on 2026-10-06 (after the Phase 1 review), replacing the earlier 2026-10-06 wording.
 */
export const PODCAST_EPISODE_AI_LINE = "AI-generated: Everything in this episode was written and voiced by AI from this week's news. People built and oversee the system but don't write or edit individual episodes."

/**
 * The same line for an episode a person reviewed and edited ("Edited by a person" ticked).
 * PENDING THE OWNER'S CONFIRMATION (plan open question 5, .context/ai-transparency.md §11): an
 * approval was relayed to an agent by a workflow on 2026-10-06, not given in the owner's own words.
 */
export const PODCAST_EPISODE_AI_LINE_EDITED = "AI-generated: Everything in this episode was written and voiced by AI from this week's news. A person reviewed and edited this episode."

/**
 * Whether the owner has confirmed `PODCAST_EPISODE_AI_LINE_EDITED` in his own words. While false, an
 * episode marked "Edited by a person" is never listed (`editedAiLineRefusal` in podcastGuards.ts).
 * Set it to true, with the date, only on the owner's own confirmation.
 */
export const PODCAST_EPISODE_AI_LINE_EDITED_CONFIRMED: boolean = false

/** The episode's AI line: the edited wording when a person changed the stories or the script. */
export function podcastEpisodeAiLine(humanEdited: boolean): string {
  return humanEdited ? PODCAST_EPISODE_AI_LINE_EDITED : PODCAST_EPISODE_AI_LINE
}

/**
 * The show's standing description (feed channel, iTunes summary, the public JSON and page).
 * Approved by the owner on 2026-10-06 (plan open question 1).
 */
export const PODCAST_SHOW_DESCRIPTION =
  "A weekly five-minute briefing on the news that matters most to humanity. Written and voiced by AI, based on Actually Relevant's AI analysis of the week's news."

/** Carousel: pixel footer on every slide, the post text line, and the alt-text prefix. */
export const CAROUSEL_COPY = {
  slideFooter: 'actuallyrelevant.news · AI-generated',
  postText: 'The headlines and summaries in these slides are AI-generated.',
  altTextPrefix: 'AI-generated summary: ',
} as const
