/**
 * Visible AI disclosure copy outside the website (EU AI Act Art. 50(4)): RSS, public API docs,
 * newsletter, social posts and bios, podcast, carousel. Approved by the owner on 2026-09-25
 * (label copy review, items ACR-5 to ACR-11, ACR-17, ACR-18). The website's copy lives in
 * client/src/components/ai/aiDisclosureCopy.ts. Change wording here, not at the call sites,
 * and update .context/ai-transparency.md in the same change.
 */

/** Prefix of every RSS item description. */
export const RSS_ITEM_PREFIX = '[AI-generated] '

/** RSS channel description; per-issue feeds lead with the issue name. */
export function rssChannelDescription(issueName?: string): string {
  if (!issueName) return 'News that matters to humanity. Written and curated by AI.'
  return `${issueName}: news that matters to humanity. Written and curated by AI.`
}

/** Note to republishers in the OpenAPI `info.description`. */
export const OPENAPI_REPUBLISHER_NOTE =
  'Story titles, labels, summaries, blurbs, and analyses are generated by AI and are not reviewed by an editor. ' +
  'If you republish them, label them as AI-generated.'

/** First sentence of every AI-generated field's OpenAPI description. */
export const OPENAPI_AI_FIELD_PREFIX = 'AI-generated. '

/** Newsletter label directly under the week title; the lead-in is set in bold. */
export const NEWSLETTER_TOP_LABEL = {
  lead: 'AI-generated:',
  text: 'AI selected the stories in this issue and wrote the intro, headlines, and summaries.',
} as const

/** Last segment of the metadata line in every Bluesky and Mastodon post. */
export const SOCIAL_POST_AI_SEGMENT = 'AI-generated'

/** Bio of the automated Bluesky and Mastodon accounts. */
export function socialBotBio(sourceCount: number): string {
  return `Automated account. Posts are generated by AI from ${sourceCount} news sources. actuallyrelevant.news`
}

/**
 * Spoken first turn of every podcast episode (HOST_A), added in code before the model's dialogue.
 * Approved by the owner on 2026-10-06 (after the Phase 1 review), replacing the 2026-10-05 wording.
 */
export const PODCAST_OPENER = "Everything you're about to hear was written and voiced by AI from this week's news."

/**
 * First line of every episode's show notes (and, from publication on, its feed description).
 * Approved by the owner on 2026-10-06 (after the Phase 1 review), replacing the earlier 2026-10-06 wording.
 */
export const PODCAST_EPISODE_AI_LINE = "AI-generated: Everything in this episode was written and voiced by AI from this week's news. People built and oversee the system but don't write or edit individual episodes."

/**
 * The same line for an episode a person reviewed and edited ("Edited by a person" ticked).
 * Owner-approved wording (plan open question 5): approved by Odin Mühlenbein in session, 2026-10-06.
 */
export const PODCAST_EPISODE_AI_LINE_EDITED = "AI-generated: Everything in this episode was written and voiced by AI from this week's news. A person reviewed and edited this episode."

/**
 * Whether the owner has confirmed `PODCAST_EPISODE_AI_LINE_EDITED` in his own words. While false, an
 * episode marked "Edited by a person" is never listed (`editedAiLineRefusal` in podcastGuards.ts).
 * Set to true only on the owner's own confirmation: approved by Odin Mühlenbein in session, 2026-10-06.
 */
export const PODCAST_EPISODE_AI_LINE_EDITED_CONFIRMED: boolean = true

/** Spoken last turn of every weekly episode (HOST_A), added in code after the model's outro. */
export const PODCAST_SIGN_OFF = "That's it for this week. Tell us what you think on actuallyrelevant.news. Thanks for listening."

/** The kinds of episode, as the schema's `PodcastKind` enum names them. */
export type PodcastCopyKind = 'weekly' | 'standalone'

export interface PodcastEpisodeCopy {
  /** Spoken first turn (HOST_A), before the model's intro. */
  opener: string
  /** Spoken last turn (HOST_A), after the model's outro. */
  signOff: string
  /** First line of the show notes, the feed description, the public JSON and the ID3 comment. */
  aiLine: string
  /** The same line for an episode marked "Edited by a person". */
  aiLineEdited: string
}

/**
 * The episode copy by kind. Weekly: the owner-approved constants above, unchanged. Standalone (an
 * episode built by hand from any published stories, which may come from different weeks): the
 * wording the coordinator relayed on 2026-10-07 as the owner's decision. It goes public only once
 * `PODCAST_STANDALONE_COPY_CONFIRMED` is true.
 */
export const PODCAST_EPISODE_COPY: Record<PodcastCopyKind, PodcastEpisodeCopy> = {
  weekly: {
    opener: PODCAST_OPENER,
    signOff: PODCAST_SIGN_OFF,
    aiLine: PODCAST_EPISODE_AI_LINE,
    aiLineEdited: PODCAST_EPISODE_AI_LINE_EDITED,
  },
  standalone: {
    opener: "Everything you're about to hear was written and voiced by AI from selected news stories.",
    signOff: "That's it for this episode. Tell us what you think on actuallyrelevant.news. Thanks for listening.",
    aiLine: "AI-generated: Everything in this episode was written and voiced by AI from news stories a person selected. People built and oversee the system but don't write or edit individual episodes.",
    aiLineEdited: 'AI-generated: Everything in this episode was written and voiced by AI from news stories a person selected. A person reviewed and edited this episode.',
  },
}

/**
 * Whether the owner has confirmed the standalone wording in `PODCAST_EPISODE_COPY.standalone` in his
 * own words. While false, a standalone episode is never voiced live (`voiceEpisode`) or listed
 * (`publishRefusal`); dry runs still work. Set to true only on the owner's own confirmation.
 */
export const PODCAST_STANDALONE_COPY_CONFIRMED: boolean = false

/** The spoken opener of an episode of this kind. */
export function podcastOpener(kind: PodcastCopyKind): string {
  return PODCAST_EPISODE_COPY[kind].opener
}

/** The spoken sign-off of an episode of this kind. */
export function podcastSignOff(kind: PodcastCopyKind): string {
  return PODCAST_EPISODE_COPY[kind].signOff
}

/** The episode's AI line: the edited wording when a person changed the stories or the script. */
export function podcastEpisodeAiLine(humanEdited: boolean, kind: PodcastCopyKind): string {
  const copy = PODCAST_EPISODE_COPY[kind]
  return humanEdited ? copy.aiLineEdited : copy.aiLine
}

/**
 * The show's standing description (feed channel, iTunes summary, the public JSON and page).
 * Approved by the owner on 2026-10-06 (plan open question 1).
 */
export const PODCAST_SHOW_DESCRIPTION =
  "A weekly five-minute briefing on the news that matters most to humanity. Written and voiced by AI, based on Actually Relevant's AI analysis of the week's news."

/** Carousel: pixel footer on every slide, the post text line, and the alt-text prefix. */
export const CAROUSEL_COPY = {
  slideFooter: 'actuallyrelevant.news · AI-generated',
  postText: 'The headlines and summaries in these slides are AI-generated.',
  altTextPrefix: 'AI-generated summary: ',
} as const
