import 'zod-openapi/extend'
import { z } from 'zod'
import { createDocument } from 'zod-openapi'
import { AI_GENERATED_STORY_FIELDS, IPTC_TRAINED_ALGORITHMIC_MEDIA } from './aiProvenance.js'

// --- Reusable schemas ---

const issueRefSchema = z.object({
  name: z.string().openapi({ example: 'Planet & Climate' }),
  slug: z.string().openapi({ example: 'planet-climate' }),
}).openapi({ ref: 'IssueRef' })

const feedRefSchema = z.object({
  id: z.string().uuid(),
  title: z.string().openapi({ example: 'The Guardian Environment' }),
  displayTitle: z.string().nullable().openapi({ example: 'The Guardian' }),
  issue: issueRefSchema.nullable(),
}).openapi({ ref: 'FeedRef' })

const aiGeneratedSchema = z.object({
  fields: z.array(z.enum(AI_GENERATED_STORY_FIELDS)).openapi({
    description: 'Names of the fields in this story object whose text was generated by an AI model. Only fields that carry a value are listed.',
    example: ['title', 'titleLabel', 'summary', 'relevanceReasons', 'antifactors'],
  }),
  model: z.string().openapi({
    description:
      'Id of the OpenAI model configured for story analysis when this response was served. ' +
      'Per-story model ids are not recorded, so stories analyzed before a model change were generated by an earlier model.',
    example: 'gpt-6-luna',
  }),
  digitalSourceType: z.literal(IPTC_TRAINED_ALGORITHMIC_MEDIA).openapi({
    description: 'IPTC Digital Source Type term for content created by a trained algorithmic model.',
  }),
}).openapi({
  ref: 'AiGenerated',
  description:
    'Machine-readable marker of the AI-generated fields in this story. ' +
    'Unsigned metadata in the API response: it is not a watermark, and text copied out of the response does not carry it.',
})

const publicStorySchema = z.object({
  id: z.string().uuid(),
  slug: z.string().nullable().openapi({ example: 'new-coral-reef-discovered-pacific' }),
  sourceUrl: z.string().url().openapi({ example: 'https://example.com/article' }),
  sourceTitle: z.string().openapi({
    description: 'Original headline of the source article (not AI-generated).',
    example: 'Major climate breakthrough announced',
  }),
  title: z.string().nullable().openapi({
    description: 'Headline written by an AI model.',
    example: 'Scientists announce major climate breakthrough',
  }),
  titleLabel: z.string().nullable().openapi({ description: 'Short topic label written by an AI model.', example: 'Climate' }),
  dateCrawled: z.string().datetime(),
  datePublished: z.string().datetime().nullable(),
  status: z.enum(['published']),
  relevancePre: z.number().int().min(0).max(10).nullable().openapi({
    description: 'Pre-assessment relevance rating assigned by an AI model.',
  }),
  relevance: z.number().int().min(0).max(10).nullable().openapi({
    description: 'Relevance rating assigned by an AI model.',
    example: 8,
  }),
  emotionTag: z.enum(['uplifting', 'frustrating', 'scary', 'calm']).nullable().openapi({
    description: 'Emotional tone assigned by an AI model.',
  }),
  summary: z.string().nullable().openapi({
    description: 'Summary written by an AI model.',
    example: 'Researchers have developed a new carbon capture method...',
  }),
  quote: z.string().nullable().openapi({
    description: 'Key quote selected from the source article by an AI model, which translates it to English when the source is in another language.',
  }),
  quoteAttribution: z.string().nullable().openapi({ description: 'Attribution of the quote, written by an AI model.' }),
  marketingBlurb: z.string().nullable().openapi({ description: 'Short teaser written by an AI model.' }),
  relevanceReasons: z.string().nullable().openapi({
    description: 'Reasons the story matters, written by an AI model as Markdown bullet points, one per line.',
  }),
  relevanceSummary: z.string().nullable().openapi({ description: 'Short relevance summary written by an AI model.' }),
  antifactors: z.string().nullable().openapi({
    description: 'Caveats written by an AI model as Markdown bullet points, one per line.',
  }),
  issue: issueRefSchema.nullable(),
  feed: feedRefSchema,
  aiGenerated: aiGeneratedSchema,
}).openapi({ ref: 'PublicStory' })

const paginationMeta = {
  total: z.number().int().openapi({ example: 142 }),
  page: z.number().int().openapi({ example: 1 }),
  pageSize: z.number().int().openapi({ example: 25 }),
  totalPages: z.number().int().openapi({ example: 6 }),
}

const storyListResponseSchema = z.object({
  data: z.array(publicStorySchema),
  ...paginationMeta,
}).openapi({ ref: 'StoryListResponse' })

const makeADifferenceSchema = z.object({
  label: z.string().openapi({ example: 'Donate to reforestation' }),
  url: z.string().url().openapi({ example: 'https://example.org/donate' }),
})

const publicIssueSchema: z.ZodType<any> = z.object({
  id: z.string().uuid(),
  name: z.string().openapi({ example: 'Planet & Climate' }),
  slug: z.string().openapi({ example: 'planet-climate' }),
  description: z.string(),
  intro: z.string(),
  evaluationIntro: z.string(),
  evaluationCriteria: z.array(z.string()),
  makeADifference: z.array(makeADifferenceSchema),
  parentId: z.string().uuid().nullable(),
  sourceNames: z.array(z.string()),
  children: z.array(z.lazy(() => publicIssueSchema)).optional(),
}).openapi({ ref: 'PublicIssue' })

const emotionBucketSchema = z.object({
  uplifting: z.array(publicStorySchema),
  calm: z.array(publicStorySchema),
  negative: z.array(publicStorySchema),
})

const homepageResponseSchema = z.object({
  issues: z.array(publicIssueSchema),
  storiesByIssue: z.record(z.string(), emotionBucketSchema),
}).openapi({ ref: 'HomepageResponse' })

const errorResponseSchema = z.object({
  error: z.string().openapi({ example: 'Not found' }),
}).openapi({ ref: 'ErrorResponse' })

// --- Document ---
// Only include public endpoints advertised on the /free-api landing page.
// Internal endpoints (subscribe, sitemap, etc.) should not appear here.

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function getOpenAPIDocument(): any {
  return createDocument({
    openapi: '3.1.0',
    info: {
      title: 'Actually Relevant API',
      version: '0.1.0',
      description:
        'Public API for Actually Relevant — an AI-curated news platform that evaluates article relevance to humanity. ' +
        'Access published stories, issues, homepage data, and RSS feeds. No authentication required.',
      contact: {
        name: 'Actually Relevant',
        url: 'https://actuallyrelevant.news',
      },
    },
    servers: [
      { url: process.env.API_URL || 'https://actually-relevant-api.onrender.com', description: 'Production' },
    ],
    paths: {
      '/api/homepage': {
        get: {
          operationId: 'getHomepage',
          summary: 'Get homepage data',
          description:
            'Returns all issues and their stories grouped by emotion tag (uplifting, calm, negative). ' +
            'Used by the client to power the positivity slider without additional API calls.',
          tags: ['Homepage'],
          responses: {
            '200': {
              description: 'Homepage data with issues and emotion-bucketed stories',
              content: {
                'application/json': { schema: homepageResponseSchema },
              },
            },
          },
        },
      },
      '/api/stories': {
        get: {
          operationId: 'listStories',
          summary: 'List published stories',
          description:
            'Returns a paginated list of published stories. Supports filtering by issue and semantic search.',
          tags: ['Stories'],
          parameters: [
            {
              name: 'page',
              in: 'query',
              schema: { type: 'integer', default: 1, minimum: 1 },
              description: 'Page number',
            },
            {
              name: 'pageSize',
              in: 'query',
              schema: { type: 'integer', default: 25, minimum: 1, maximum: 100 },
              description: 'Number of stories per page',
            },
            {
              name: 'issueSlug',
              in: 'query',
              schema: { type: 'string' },
              description: 'Filter by issue slug (e.g., "planet-climate")',
            },
            {
              name: 'search',
              in: 'query',
              schema: { type: 'string', minLength: 2, maxLength: 200 },
              description: 'Semantic search query — searches by meaning, not just keywords. Subject to a stricter rate limit (20 requests per 15 minutes).',
            },
            {
              name: 'emotionTags',
              in: 'query',
              schema: { type: 'string' },
              description: 'Comma-separated emotion tags to filter by (e.g., "uplifting" or "uplifting,calm")',
            },
          ],
          responses: {
            '200': {
              description: 'Paginated list of published stories',
              content: {
                'application/json': { schema: storyListResponseSchema },
              },
            },
          },
        },
      },
      '/api/stories/{slug}': {
        get: {
          operationId: 'getStory',
          summary: 'Get a single story',
          description: 'Returns a single published story by its URL slug.',
          tags: ['Stories'],
          parameters: [
            {
              name: 'slug',
              in: 'path',
              required: true,
              schema: { type: 'string' },
              description: 'Story URL slug',
            },
          ],
          responses: {
            '200': {
              description: 'Story details',
              content: {
                'application/json': { schema: publicStorySchema },
              },
            },
            '404': {
              description: 'Story not found',
              content: {
                'application/json': { schema: errorResponseSchema },
              },
            },
          },
        },
      },
      '/api/issues': {
        get: {
          operationId: 'listIssues',
          summary: 'List all issues',
          description:
            'Returns all issues with their hierarchy (parents contain children). ' +
            'Cached for 5 minutes.',
          tags: ['Issues'],
          responses: {
            '200': {
              description: 'List of issues with hierarchy',
              content: {
                'application/json': {
                  schema: z.array(publicIssueSchema),
                },
              },
            },
          },
        },
      },
      '/api/issues/{slug}': {
        get: {
          operationId: 'getIssue',
          summary: 'Get a single issue',
          description: 'Returns a single issue by its URL slug, including children and source names.',
          tags: ['Issues'],
          parameters: [
            {
              name: 'slug',
              in: 'path',
              required: true,
              schema: { type: 'string' },
              description: 'Issue URL slug (e.g., "planet-climate")',
            },
          ],
          responses: {
            '200': {
              description: 'Issue details',
              content: {
                'application/json': { schema: publicIssueSchema },
              },
            },
            '404': {
              description: 'Issue not found',
              content: {
                'application/json': { schema: errorResponseSchema },
              },
            },
          },
        },
      },
      '/api/feed': {
        get: {
          operationId: 'getRssFeed',
          summary: 'RSS feed (all stories)',
          description: 'Returns an RSS 2.0 feed of all published stories. Cached for 15 minutes.',
          tags: ['Feed'],
          responses: {
            '200': {
              description: 'RSS 2.0 XML feed',
              content: {
                'application/rss+xml': {
                  schema: { type: 'string' },
                },
              },
            },
          },
        },
      },
      '/api/feed/{issueSlug}': {
        get: {
          operationId: 'getRssFeedByIssue',
          summary: 'RSS feed (per issue)',
          description: 'Returns an RSS 2.0 feed filtered to a specific issue. Cached for 15 minutes.',
          tags: ['Feed'],
          parameters: [
            {
              name: 'issueSlug',
              in: 'path',
              required: true,
              schema: { type: 'string' },
              description: 'Issue slug to filter by',
            },
          ],
          responses: {
            '200': {
              description: 'RSS 2.0 XML feed for the specified issue',
              content: {
                'application/rss+xml': {
                  schema: { type: 'string' },
                },
              },
            },
            '404': {
              description: 'Issue not found',
              content: {
                'application/json': { schema: errorResponseSchema },
              },
            },
          },
        },
      },
    },
    components: {
      schemas: {},
    },
    tags: [
      { name: 'Homepage', description: 'Homepage data with emotion-bucketed stories' },
      { name: 'Stories', description: 'Published story listing and detail' },
      { name: 'Issues', description: 'Issue categories and hierarchy' },
      { name: 'Feed', description: 'RSS 2.0 feeds' },
    ],
  })
}
