import { describe, it, expect } from 'vitest'
import { getOpenAPIDocument } from './openapi.js'
import { AI_GENERATED_PODCAST_DETAIL_FIELDS, AI_GENERATED_PODCAST_FIELDS, AI_GENERATED_STORY_FIELDS } from './aiProvenance.js'

describe('getOpenAPIDocument', () => {
  const doc = getOpenAPIDocument()
  const schemas = doc.components.schemas

  it('documents the aiGenerated marker on every public story', () => {
    expect(schemas.PublicStory.required).toContain('aiGenerated')
    expect(schemas.PublicStory.properties.aiGenerated.$ref).toBe('#/components/schemas/AiGenerated')
  })

  it('lists exactly the registry fields as possible AI-generated field names', () => {
    expect(schemas.AiGenerated.properties.fields.items.enum).toEqual([...AI_GENERATED_STORY_FIELDS])
  })

  it('labels every AI-generated field of the story schema, then describes it', () => {
    for (const field of AI_GENERATED_STORY_FIELDS) {
      const description: string = schemas.PublicStory.properties[field].description
      expect(description.startsWith('AI-generated. '), field).toBe(true)
      expect(description.length, field).toBeGreaterThan('AI-generated. '.length)
    }
  })

  it('labels every AI-generated field of a podcast episode and lists exactly those in its marker', () => {
    const episode = schemas.PodcastEpisode
    expect(episode.properties.aiGenerated.properties.fields.items.enum).toEqual([...AI_GENERATED_PODCAST_FIELDS])
    for (const field of AI_GENERATED_PODCAST_FIELDS) {
      expect(episode.properties[field].description.startsWith('AI-generated. '), field).toBe(true)
    }
    expect(doc.paths['/api/podcast'].get.responses['200']).toBeDefined()
  })

  it('labels the episode detail transcript as AI-generated and lists it in the detail marker', () => {
    const detail = schemas.PodcastEpisodeDetail
    expect(detail.properties.aiGenerated.properties.fields.items.enum).toEqual([...AI_GENERATED_PODCAST_DETAIL_FIELDS])
    for (const field of AI_GENERATED_PODCAST_DETAIL_FIELDS) {
      expect(detail.properties[field].description.startsWith('AI-generated. '), field).toBe(true)
    }
    expect(doc.paths['/api/podcast/episodes/{id}'].get.responses['404']).toBeDefined()
  })

  it('asks republishers to label the AI text, in the API description', () => {
    expect(doc.info.description).toContain(
      'Story titles, labels, summaries, blurbs, and analyses are generated by AI and are not reviewed by an editor. ' +
        'If you republish them, label them as AI-generated.',
    )
  })
})
