import { describe, it, expect, vi } from 'vitest'
import { render, screen } from '@testing-library/react'
import { MemoryRouter } from 'react-router-dom'
import { HelmetProvider } from 'react-helmet-async'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import MethodologyPage from './MethodologyPage'
import StewardshipPage from './StewardshipPage'
import ThankYouPage from './ThankYouPage'

vi.mock('../components/SubscribeProvider', () => ({
  useSubscribe: () => ({ openSubscribe: vi.fn() }),
}))

vi.mock('../hooks/useSources', () => ({
  useSources: () => ({
    data: {
      byRegion: { 'North America': ['Reuters', 'AP'] },
      byIssue: { 'Planet & Climate': ['Mongabay', 'Grist'] },
      totalCount: 82,
    },
    isLoading: false,
  }),
}))

function renderPage(component: React.ReactElement) {
  const queryClient = new QueryClient({ defaultOptions: { queries: { retry: false } } })
  return render(
    <QueryClientProvider client={queryClient}>
      <HelmetProvider>
        <MemoryRouter>{component}</MemoryRouter>
      </HelmetProvider>
    </QueryClientProvider>,
  )
}

describe('MethodologyPage', () => {
  it('renders dynamic source count from useSources hook', () => {
    renderPage(<MethodologyPage />)
    expect(screen.getByText(/82 curated news sources/)).toBeInTheDocument()
  })

  it('says what AI generates and selects, that no editor reviews it, and where to report a wrong label', () => {
    renderPage(<MethodologyPage />)
    const item = screen.getByText("We don't do original reporting.").closest('li')!
    expect(item.textContent!.replace(/\s+/g, ' ')).toBe(
      "We don't do original reporting. Every story links to the original source article. " +
        'Headlines, summaries, blurbs, relevance analyses, social posts, and the newsletter intro are generated by AI. ' +
        'AI also rates each story, selects the stories we publish, and sets the emotion tag behind the dial. ' +
        'Quotes are selected by AI and translated into English where needed. ' +
        "No editor reviews anything before it's published. " +
        "Spotted AI content without a label, or a label that's wrong? Tell us on the feedback page.",
    )
    expect(screen.getByRole('link', { name: 'feedback page' })).toHaveAttribute('href', '/feedback')
    expect(screen.queryByText(/clearly labeled/)).toBeNull()
  })
})

describe('StewardshipPage', () => {
  it('renders heading and dynamic source count', () => {
    renderPage(<StewardshipPage />)
    expect(screen.getByRole('heading', { level: 1, name: /long-term home/i })).toBeInTheDocument()
    expect(screen.getByText(/82\+/)).toBeInTheDocument()
  })
})

describe('ThankYouPage', () => {
  it('renders heading and credit sections', () => {
    renderPage(<ThankYouPage />)
    expect(screen.getByRole('heading', { level: 1, name: /thank you/i })).toBeInTheDocument()
    expect(screen.getByRole('heading', { name: /frontend/i })).toBeInTheDocument()
    expect(screen.getByRole('heading', { name: /backend/i })).toBeInTheDocument()
  })
})
