/**
 * DRAFT wording for the AI disclosure components (EU AI Act Art. 50(4)/(5)),
 * as proposed in the 2026-09-25 assessment (§5.2). The owner is reviewing all
 * label copy, so AiBadge, AiLabel and SiteAiNotice are not mounted anywhere yet.
 * Settle the wording here, then mount the components (see .context/ai-transparency.md).
 */
export const AI_DISCLOSURE_COPY = {
  /** Visible main element of every label; the EU icons use "AI" too. */
  badgeText: 'AI',
  /** What screen readers announce for a standalone badge. */
  badgeAccessibleName: 'AI-generated',
  labelText: 'AI-generated',
  siteNotice: 'Headlines, summaries and analyses on this site are generated by AI and are not reviewed by an editor.',
  siteNoticeLinkText: 'How it works',
  siteNoticeLinkHref: '/methodology',
} as const
