import { describe, it, expect } from 'vitest'
import type { AppBskyActorProfile } from '@atproto/api'
import { BOT_SELF_LABEL, mastodonBotUpdate, withBotProfile } from './socialBotProfile.js'
import { socialBotBio } from '../lib/aiLabelCopy.js'

const bio = socialBotBio(82)

describe('socialBotBio', () => {
  it('names the source count in the approved bio', () => {
    expect(bio).toBe('Automated account. Posts are generated by AI from 82 news sources. actuallyrelevant.news')
  })

  it('fits the Bluesky (256 graphemes) and Mastodon (500 characters) bio limits', () => {
    expect(socialBotBio(1000).length).toBeLessThanOrEqual(256)
  })
})

describe('withBotProfile', () => {
  const existing: AppBskyActorProfile.Record = {
    $type: 'app.bsky.actor.profile',
    displayName: 'Actually Relevant',
    description: 'Curated with care by AI',
    website: 'https://actuallyrelevant.news',
  }

  it('sets the bio and adds the bot self-label, keeping every other field', () => {
    const updated = withBotProfile(existing, bio)
    expect(updated).toEqual({
      ...existing,
      description: bio,
      labels: { $type: 'com.atproto.label.defs#selfLabels', values: [{ val: BOT_SELF_LABEL }] },
    })
  })

  it('keeps existing self-labels and does not add the bot label twice', () => {
    const labelled = withBotProfile(
      {
        ...existing,
        labels: { $type: 'com.atproto.label.defs#selfLabels', values: [{ val: '!no-unauthenticated' }, { val: 'bot' }] },
      },
      bio,
    )
    expect(labelled.labels).toEqual({
      $type: 'com.atproto.label.defs#selfLabels',
      values: [{ val: '!no-unauthenticated' }, { val: 'bot' }],
    })
  })

  it('creates a profile record when the account has none yet', () => {
    expect(withBotProfile(undefined, bio)).toEqual({
      description: bio,
      labels: { $type: 'com.atproto.label.defs#selfLabels', values: [{ val: BOT_SELF_LABEL }] },
    })
  })
})

describe('mastodonBotUpdate', () => {
  it('changes only the bio and the bot flag', () => {
    expect(mastodonBotUpdate(bio)).toEqual({ note: bio, bot: true })
  })
})
