/**
 * Mark the automated Bluesky and Mastodon accounts as bots and set their bios
 * (label copy review ACR-11 and ACR-12, .context/ai-transparency.md).
 *
 * - Bio (both accounts): "Automated account. Posts are generated by AI from {N} news sources.
 *   actuallyrelevant.news", with N the number of active feeds when the script runs (the same
 *   count as GET /api/sources `totalCount` and the site's source count).
 * - Mastodon: bot=true. Bluesky: the "bot" self-label on the profile record.
 * - Every other profile field (display name, avatar, banner, links, other self-labels) is kept.
 *
 * Dry run by default: prints the current and the proposed values and changes nothing.
 *
 *   npm run social:bot-profile --prefix server          # dry run
 *   npm run social:bot-profile:apply --prefix server    # writes to both live accounts
 *
 * Needs the production credentials in server/.env: DATABASE_URL (for the source count),
 * BLUESKY_HANDLE + BLUESKY_APP_PASSWORD, MASTODON_URL + MASTODON_TOKEN. The Mastodon token must
 * carry the read:accounts and write:accounts scopes; a posting-only token gets a 403.
 */
import dotenv from 'dotenv'
import path from 'path'
import { fileURLToPath, pathToFileURL } from 'url'
import { AtpAgent } from '@atproto/api'
import { createRestAPIClient } from 'masto'
import { socialBotBio } from '../lib/aiLabelCopy.js'
import { BOT_SELF_LABEL, mastodonBotUpdate, withBotProfile } from '../services/socialBotProfile.js'
import type { withRetry as WithRetry } from '../lib/retry.js'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
dotenv.config({ path: path.resolve(__dirname, '../../.env') })

const APPLY = process.argv.includes('--apply')

function labelList(labels: { val: string }[] | undefined): string {
  return labels?.length ? labels.map((label) => label.val).join(', ') : '(none)'
}

async function setBlueskyProfile(
  cfg: { handle: string; appPassword: string; serviceUrl: string },
  bio: string,
  retry: typeof WithRetry,
) {
  if (!cfg.handle || !cfg.appPassword) {
    console.log('\nBluesky: BLUESKY_HANDLE or BLUESKY_APP_PASSWORD not set, skipped.')
    return
  }
  const agent = new AtpAgent({ service: cfg.serviceUrl })
  await retry(() => agent.login({ identifier: cfg.handle, password: cfg.appPassword }))

  const before = await retry(() => agent.getProfile({ actor: cfg.handle }))
  console.log(`\nBluesky @${cfg.handle}`)
  console.log(`  current bio:    ${before.data.description ?? '(none)'}`)
  console.log(`  current labels: ${labelList(before.data.labels)}`)
  if (!APPLY) {
    console.log(`  would set:      bio above, plus the "${BOT_SELF_LABEL}" self-label`)
    return
  }

  await retry(() => agent.upsertProfile((existing) => withBotProfile(existing, bio)))
  const after = await retry(() => agent.getProfile({ actor: cfg.handle }))
  console.log(`  new bio:        ${after.data.description ?? '(none)'}`)
  console.log(`  new labels:     ${labelList(after.data.labels)}`)
}

async function setMastodonProfile(
  cfg: { instanceUrl: string; accessToken: string },
  bio: string,
  retry: typeof WithRetry,
) {
  if (!cfg.instanceUrl || !cfg.accessToken) {
    console.log('\nMastodon: MASTODON_URL or MASTODON_TOKEN not set, skipped.')
    return
  }
  const client = createRestAPIClient({ url: cfg.instanceUrl, accessToken: cfg.accessToken })

  const before = await retry(() => client.v1.accounts.verifyCredentials())
  console.log(`\nMastodon @${before.acct}`)
  console.log(`  current bio: ${before.source.note || '(none)'}`)
  console.log(`  bot flag:    ${before.bot}`)
  if (!APPLY) {
    console.log('  would set:   bio above, plus bot=true')
    return
  }

  const after = await retry(() => client.v1.accounts.updateCredentials(mastodonBotUpdate(bio)))
  console.log(`  new bio:     ${after.source.note || '(none)'}`)
  console.log(`  bot flag:    ${after.bot}`)
}

async function main() {
  // Imported after dotenv, because config.ts reads the environment when it loads
  const { config } = await import('../config.js')
  const { default: prisma } = await import('../lib/prisma.js')
  const { withRetry } = await import('../lib/retry.js')

  console.log(`Social bot profiles, mode: ${APPLY ? 'APPLY (writes to the live accounts)' : 'DRY RUN (changes nothing)'}`)

  const sourceCount = await prisma.feed.count({ where: { active: true } })
  await prisma.$disconnect()
  if (sourceCount === 0) {
    throw new Error('No active feeds found. Check DATABASE_URL before writing a bio that names the source count.')
  }
  const bio = socialBotBio(sourceCount)
  console.log(`Active news sources: ${sourceCount}`)
  console.log(`Bio: ${bio}`)

  await setBlueskyProfile(config.bluesky, bio, withRetry)
  await setMastodonProfile(config.mastodon, bio, withRetry)

  if (!APPLY) console.log('\nDry run complete. Re-run with social:bot-profile:apply to write these values.')
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((err) => {
    console.error('Fatal error:', err)
    process.exit(1)
  })
}
